#!/bin/sh
WM=${WM:-dwm}
[ -f "$HOME/.config/x11/Xresources" ] && which xrdb && xrdb "$HOME/.config/x11/Xresources"
[ -f "$HOME/.config/x11/xprofile" ]   && . "$HOME/.config/x11/xprofile"
! pidof pipewire && command -v pipewire && pipewire &
! pidof pipewire-pulse && command -v pipewire-pulse && pipewire-pulse &
exec "$WM"
