#!/bin/sh
# Basic Setup
sxhkdrc=$(mktemp)
cat "${HOME}/.config/sxhkd/${WM}sx" "${HOME}/.config/sxhkd/base" >"$sxhkdrc"
which setxkbmap && setxkbmap -option caps:escape

# X settings
if which xset; then
    xset r rate 300 50 &
    xset b off &
fi
which xhost && xhost +local: & # allow chroots to connect to the X server

# One Time Run
which bri && bri set 35
which hsetroot && hsetroot -solid slategray

# Unleash the daemons!!!
which sxhkd && sxhkd -c "$sxhkdrc" &
if which picom; then
    picom &
else
    if which xcompmgr; then
        xcompmgr -c &
    fi
fi
[ "$WM" = exwm ] && {
    which hsetroot && hsetroot -full $HOME/Pictures/Wallpapers/rockycoast.jpg
}
[ "$WM" = dwm ] && {
    which sb-py && sb-py dwm &
}
