#!/bin/sh -e
[ $(basename $PWD) = dots ] || exit 1

if ! command -v sbcl; then
    echo "SBCL must be installed for the dotfiles to be properly installed!"
    exit 1
fi

sbcl --load stow.lisp \
     --eval "(stow:install-dots)" \
     --eval "(quit)"

# Picom behaves strangely if the file is a symlink.
if [ -e "$HOME/.config/picom.conf" ]; then
    rm "$HOME/.config/picom.conf" && cp X/.config/picom.conf "$HOME/.config/picom.conf"
fi
