;;; init --- my Emacs init file

;;; Commentary:

;; This is my personal Emacs configuration.  It may be of use to you,
;; as I have configured quite a number of packages.  However, there is
;; an emphasis on lightweight or builtin packages in Emacs.  Also, by
;; default, every package is explicitly deferred unless if it is
;; absolutely required at init time.  Because of this, my init time hovers
;; around 0.5 to 1 second.  This could be reduced if you don't use evil.

(defun me/package-bootstrap ()
  "Function to bootstrap package.el."
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  ;; Only install 'use-package' if Emacs version is below 29,
  ;; and if use-package is not already installed.
  (if (and (< emacs-major-version 29)
           (not (package-installed-p 'use-package)))
      (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-ensure t
        use-package-compute-statistics t))

(me/package-bootstrap)

(setq me/delete-trailing-whitespace nil)

(defmacro me/emacs-N-progn (N &rest body)
  (when (>= emacs-major-version N)
    `(progn ,@body)))

(me/emacs-N-progn
 30
 (use-package package-vc
   :ensure nil
   :demand t
   :custom
   (package-vc-allow-build-commands t)))

;; FIXME: add optional argument to determine whether or not command will be evaluated again.
(defmacro me/eval-form-on-first-command-run (command form &optional var-p)
  "Evaluate FORM when COMMAND is attempted to be ran for the first time.
COMMAND will be re-evaluated after FORM is evaluated.
If COMMAND is not redefined after evaluating FORM, an infinite loop will occur.

If VAR-P is provided, it will be used as the predicate var to determine if the
command has been ran before.
"
  (let ((comm-var-ran-p (intern
                         (concat
                          (symbol-name command)
                          "-"
                          (symbol-name (gensym))
                          "-p"))))
    (setq comm-var-ran-p (if var-p var-p comm-var-ran-p))
    `(progn
       (setq ,comm-var-ran-p (if (boundp ',comm-var-ran-p) ,comm-var-ran-p nil))
       (defun ,command ()
         "AUTOGENERATED by `me/eval-form-on-first-command-run` macro!"
         (interactive)
         (unless ,comm-var-ran-p
           (eval (quote ,form))
           (setq ,comm-var-ran-p t))
         (,command)))))

(defmacro me/eval-form-on-first-commands-run (command-lst form)
  (let ((comm-var-ran-p (intern
                         (concat
                          (symbol-name (car command-lst))
                          "-"
                          (symbol-name (gensym))
                          "-p"))))
    `(progn
       ,@(mapcar
          (lambda (comm)
            `(me/eval-form-on-first-command-run
              ,comm ,form ,comm-var-ran-p))
          command-lst))))

;; IE: only install/require the code whenever I begin to edit a file
;; with the associated file extension.
;; FIXME: re-implement in terms of me/eval-form-on-first-command-run
;; TODO: consider rewriting this macro as a use-package extension
(defmacro me/setup-auto-mode (file-extension major-mode &rest args)
  "FIXME: write this docstring."
  ;; NOTE: only use this for modes that you don't plan on configuring at all.

  ;; Default values for the use-package decl.
  (let ((pkg  major-mode)
        (mm   major-mode)
        (fe   file-extension)
        (body args))
    ;; Means we have args that we need to parse.
    (when args
      (if (eq (nth 0 args) :package)
          (progn
            (setq pkg  (nth 1 args))
            (setq body (seq-drop args 2)))))
    (let ((setup-fn-name
           (intern
            (concat
             "setup-"
             (symbol-name mm)
             "-"
             (symbol-name (gensym))))))
      `(progn
         (defun ,setup-fn-name ()
           "AUTOGENERATED from `me/setup-auto-mode` macro."
           (unless (fboundp ',mm)
             (use-package ,pkg)
             ,@body)
           (,mm))
         (add-to-list
          'auto-mode-alist
          '(,fe . ,setup-fn-name))))))

(defmacro with-var-value (var value &rest body)
  `(let ((old^ ,var))
     (unwind-protect
         (progn (setq ,var ,value) ,@body)
       (setq ,var old^))))


;; TODO: make macro to have `:hook (some-mode . (lambda () (use-package some-pkg ...)))`
;; be more seamless.

(defmacro me/eval-form-in-mode-hook (form mode-name)
  "FIXME: write this docstring"
  `(error "TODO")
  )

;; (enfun ) -- good conlang idea

(setq me/modal-system nil)
(use-package emacs
  :hook ((prog-mode . display-fill-column-indicator-mode)
         (before-save . (lambda ()
                          ;; Somewhat better way of deleting whitespace
                          (when (or (not vc-mode) me/delete-trailing-whitespace)
                            (delete-trailing-whitespace (point-min) (point-max)))))
         (emacs-startup . (lambda ()
                            (message "Emacs loaded in %s with %d garbage collections."
                                     (format "%.2f seconds"
                                             (float-time
                                              (time-subtract after-init-time before-init-time))) gcs-done)))
         (after-save . executable-make-buffer-file-executable-if-script-p))

  :custom
  ;; Indentation
  (default-tab-width 4)
  (tab-width 4)
  (default-fill-column 80)
  (fill-column 80)

  ;; Show column number too
  (column-number-mode t)

  ;; Be more like vim when scrolling
  (scroll-step 1)
  (scroll-conservatively 10000)
  (next-screen-context-lines 5)
  (line-move-visual nil)

  ;; Don't use file backups.
  (backup-inhibited t)
  ;; Don't ask for confirmation when opening large files.
  (large-file-warning-threshold nil)

  ;; I almost NEVER want to see the warnings buffer.
  (warning-minimum-level :emergency)
  ;; Now if only I could also disable the *Compile-Log* buffer...
  (compilation-window-height 0)
  ;; Prevent any buffer from making a new window
  (display-buffer-alist '(("\\.*" . (display-buffer-no-window))))

  ;; Better buffer naming.
  (uniquify-buffer-name-style 'post-forward)

  ;; Native Compilation.
  (package-native-compile (>= emacs-major-version 28))
  (native-comp-async-report-warnings-errors (not (>= emacs-major-version 28)))

  ;; utf-8
  (default-buffer-file-coding-system 'utf-8)

  ;; Keep custom variables from polluting this file.
  (custom-file (concat user-emacs-directory "custom.el"))

  ;; Automatically visit symlink sources.
  (find-file-visit-truename t)
  (vc-follow-symlinks t)

  (use-dialog-box nil)

  ;; Don't wrap lines
  (truncate-lines t)


  ;; Make minibuffer less stuttery.
  (read-minibuffer-restore-windows nil)

  ;; Don't prompt when trying to kill a buffer with a live process.
  (kill-buffer-query-functions
   (remq 'process-kill-buffer-query-function
         kill-buffer-query-functions))

  ;; I really really cannot stand how eldoc thinks its the most important
  ;; package that likes to take over buffers that I am referring to.
  (eldoc-echo-area-prefer-doc-buffer nil)
  (eldoc-idle-delay 0)
  :config
  ;; OS specific settings.
  (cond
   ((eq system-type 'darwin)
    (progn
      ;;(setq mac-command-modifier 'control)
      (setq mac-option-modifier 'meta) ;; This is for the gui version of emacs

      ;; Emacs on macOS has now crash too many times with no reason for me to
      ;; feel comfortable disabling this.
      (setq auto-save-default t
            auto-save-timeout 30)
      ;; Only use this package on macOS. Otherwise things on Linux and BSD
      ;; behave very very incorrectly. Linux does not have the weird shell
      ;; issues that macOS has so this package hurts *far* more than it helps.
      (use-package exec-path-from-shell
        :config
        (dolist (var '("PATH"
                       "HOMEBREW_PREFIX" "HOMEBREW_CELLAR" "HOMEBREW_REPOSITORY"
                       "VIRTUAL_ENV" "PYTHONHOME"
                       "CPPFLAGS" "LDFLAGS"
                       "SSH_AUTH_SOCK" "SSH_AGENT_PID"))
          (add-to-list 'exec-path-from-shell-variables var))
        (exec-path-from-shell-initialize))))
   (t
    (progn
      (setq auto-save-default nil))
    )
   )

  ;; Section to disable eldoc since I almost never want it around.
  ;; If I do, then I still have means of enabling it.

  (defvar me/eldoc-enabled-p nil)

  (defun me/eldoc-advice (orig &rest args)
    (when me/eldoc-enabled-p
      (apply orig args)))

  (advice-add 'eldoc-mode :around #'me/eldoc-advice)

  (defun me/toggle-eldoc (&optional arg)
    (interactive "P")
    (setq me/eldoc-enabled-p (if arg nil (not me/eldoc-enabled-p))))

  ;; Disable the C-scrolling keybinds
  (global-set-key (kbd "C-<wheel-up>")   #'ignore)
  (global-set-key (kbd "C-<wheel-down>") #'ignore)

  ;; Automatically update buffers when contents change on disk.
  (global-auto-revert-mode)
  ;; Always highlight the current line.
  (global-hl-line-mode)
  ;; Don't ask to spell out 'yes'
  (fset 'yes-or-no-p 'y-or-n-p)
  ;; utf-8
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)

  ;; ibuffer is a better version of list-buffers.
  ;; http://xahlee.info/emacs/emacs/emacs_buffer_management.html
  (defalias 'list-buffers 'ibuffer)

  ;; Prevent the scratch buffer from being killed.
  (with-current-buffer "*scratch*"
    (emacs-lock-mode 'kill))

  ;; Don't error if we can't load the custom file
  (load custom-file 'noerror)
  (setq-default indent-tabs-mode nil
                tab-width 4))

(use-package async :defer)

(use-package ux-setup :ensure nil)
(use-package ui-setup :ensure nil)
(use-package pl-setup :ensure nil)

;; Elisp programming libraries
(use-package for     :defer)
(use-package eprolog :defer)


;; (eprolog-define-prolog-predicate parent (tom bob))
;; (eprolog-define-prolog-predicate parent (bob ann))

;; (eprolog-define-prolog-predicate grandparent (_x _z)
;;   (parent _x _y)
;;   (parent _y _z))

;; ;; Query the database
;; (eprolog-query (grandparent tom _x))


;; Some packages worth looking into.
;; scratch-plus
;; magit-prime (faster magit times)
;; automoji  (discord style emoji completion)

;; (use-package vc-got :defer)
;; (use-package vc-fossil :defer)
;; (use-package vc-defer)

;; (use-package mqr :defer)

;;https://github.com/jdtsmith/comint-fold

;; (use-package doom-themes :defer)

;; TODO: Break this out into a package.
;; TODO: also make a macro to help simplify the creation of
;; the functions - it should suffice to simply provide the quoted
;; code and to have that automagically be inserted into an anonymous function.
;; Semi-Configurable modeline.


;;(make-variable-buffer-local
;;(setq me/apheleia-preferred-backend (me/get-formatter-backend))


;; I almost never want this to popup
;; (use-package eldoc-box
;;   :defer
;;   :hook ((eldoc-mode         . eldoc-box-hover-mode)))



;; https://github.com/emacs-languagetool/flymake-languagetool
;; https://github.com/emacs-languagetool
;; https://valentjn.github.io/ltex/index.html
;; https://old.reddit.com/r/emacs/comments/1b1s7wk/grammarly_in_emacs/

(me/emacs-N-progn
 31
 (defun me/make-vale-config ()
   "Write a simple vale config to `.vale.ini' in `default-directory'."
   (interactive)
   (let ((vale-cfg (concat default-directory ".vale.ini")))
     (write-region
      "StylesPath = styles

MinAlertLevel = suggestion

Packages = proselint, write-good, alex, Readability, Joblint

[*]
BasedOnStyles = Vale, proselint, write-good, alex, Readability, Joblint"
      nil
      vale-cfg))
   (shell-command "vale sync")
   (when flymake-mode (flymake-vale-maybe-load)))

 (use-package flymake-vale
   :if (executable-find "vale")
   :defer
   :vc (:url "https://github.com/tpeacock19/flymake-vale"
             :rev :newest)
   :hook (flymake-mode . flymake-vale-load)))


;; it should be possible to have this be a keyword, similar to :defer,
;; which, will actually install the package either when the file extension
;; given by :mode is encountered, or when a certain mode is requested.
;; Git frontend.
(progn
  (use-package magit
    :hook (magit-mode . (lambda ()
                          (use-package gptel-magit :after gptel))))
  (use-package forge)
  ;; (use-package magit-filenotify)
  (use-package magit-gh)
  (use-package magit-gh-pulls))

;; TODO: add a keybind to bring up vundo menu.


;; (use-package jinx
;;   :defer
;;   :hook ((emacs-startup . global-jinx-mode)
;;          (prog-mode     . (lambda () (jinx-mode -1))))
;;   :bind ([remap ispell-word] . jinx-correct))

;; Collaborative editing in Emacs.
(me/eval-form-on-first-command-run crdt-version (use-package crdt))

;; NOTE: look into this package.
;; (use-package ess-view-data
;;   :defer t)


;; Package nael is new.

;;      Status: New from melpa -- Install
;;     Archive: melpa
;;     Version: 20251215.1233
;;      Commit: 82bd9a2141f9dc18945b5a8f530c94bbc5fef3ac
;;     Summary: Major mode for Lean
;;    Requires: emacs-29.1
;;     Website: https://codeberg.org/mekeor/nael
;;    Keywords: languages
;;  Maintainer: Mekeor Melire <mekeor@posteo.de>

;; `nael-mode' is a major mode for Lean.

;; Nael is forked from Lean4-Mode:
;; https://github.com/leanprover-community/lean4-mode

;; (use-package prolog-mode
;;   :ensure nil
;;   :mode (("\\.P\\'"  . prolog-mode)
;;          ("\\.pl\\'" . prolog-mode)
;;          ("\\.m$"    . mercury-mode))

;;   )

;; https://eshelyaron.com/sweep.html
;; (use-package prolog
;;   :ensure nil
;;   :load-path "prolog"
;;   :defer
;;   ;; Have <file>.(P|pl), be recognized as prolog source files.
;;   ;; Have <file>.m be recognized as mercury source file.
;;   :mode (("\\.P\\'"  . prolog-mode)
;;          ("\\.pl\\'" . prolog-mode)
;;          ("\\.m$"    . mercury-mode))
;;   :init
;;   (let ((pl-dir (concat user-emacs-directory "prolog/")))
;;     (unless (file-exists-p pl-dir)
;;       (make-directory pl-dir)
;;       (url-copy-file "https://bruda.ca/_media/emacs/prolog.el"
;;                      (concat pl-dir "prolog.el"))))
;;   :config
;;   (setq prolog-system 'swi)
;;   ;; Custom code to allow for switching between prolog implementations.
;;   (let* ((custom-prologs '((trealla "tpl")
;;                            (scryer "scryer-prolog")))
;;          (new-prolog-program-name
;;           (seq-remove
;;            (lambda (p)
;;              (or (equal (car p) t)
;;                  (equal (cadr p) nil)))
;;            (seq-filter (lambda (p) (symbolp (car p)))
;;                        (append prolog-program-name custom-prologs)))))
;;     (dolist (prolog-pair new-prolog-program-name)
;;       (if (executable-find (cadr prolog-pair))
;;           (let* ((prolog-sys (car prolog-pair))
;;                  (prolog-exe (cadr prolog-pair))
;;                  (prolog-sym-str (symbol-name prolog-sys))
;;                  (func-name
;;                   (intern
;;                    (seq-concatenate
;;                     'string
;;                     "run-" prolog-sym-str "-prolog"))))
;;             (eval
;;              `(defun ,func-name ()
;;                 (interactive)
;;                 (let ((prolog-system ',prolog-sys)
;;                       (prolog-program-name ,prolog-exe))
;;                   (run-prolog t)))))))))

;; Custom snobol mode.
;; (use-package snobol-mode
;;   :ensure nil
;;   :init
;;   (unless (package-installed-p (intern "snobol-mode"))
;;     (package-vc-install "https://github.com/echawk/snobol-mode"
;;                         :last-release))
;;   :mode ("\\.sno" . snobol-mode))

;; Better scheme editing.
;; (use-package geiser :defer
;;   :defer
;;   :custom
;;   (geiser-active-implementations '(guile3 racket)))
;; (use-package geiser-guile
;;   :after geiser
;;   :custom (geiser-guile-binary "guile3"))

;; (use-package macrostep-geiser
;;   :after geiser-mode
;;   :hook ((geiser-mode . macrostep-geiser-setup)))

;; https://scripter.co/emacs-lisp-advice-combinators/


;; (use-package agda
;;   :ensure nil
;;   :defer
;;   :if (executable-find "agda-mode")
;;   :commands (agda2-mode)
;;   :init
;;   (load-file (shell-command-to-string "agda-mode locate")))
;; (setq completion-at-point-functions
;;       (append
;;        completion-at-point-functions
;;        (mapcar #'cape-company-to-capf
;;                (list #'dante-company))))


;; https://github.com/phantomics/april/tree/master
;; anaphora is a dependency of jpt-apl-mode.
;; (me/emacs-N-progn
;;  30
;;  (use-package anaphora :defer)
;;  (use-package jpt-apl-mode
;;    :vc (:url "https://github.com/jthing/apl-mode"
;;              :rev :newest)
;;    :defer))


;; Relational programming for Emacs (miniKanren).
;;(use-package reazon )

;; Speed reading in Emacs.
(me/emacs-N-progn
 30
 (me/eval-form-on-first-command-run
  spray-mode
  (use-package spray
    :vc (:url "https://github.com/emacsmirror/spray"
              :rev :newest)
    :commands (spray-mode))))

(use-package org
  :mode ("\\.org\\'" . org-mode)
  :hook
  (org-mode . jinx-mode)
  :init
  (setq org-edit-src-content-indentation 0
        org-confirm-babel-evaluate nil
        org-src-preserve-indentation t)
  :config
  (require 'org-tempo)
  (advice-add
   #'org-babel-execute-src-block
   :around
   (lambda (orig &rest args)
     (let ((language (org-element-property :language (org-element-at-point))))
       (unless (cdr (assoc (intern language) org-babel-load-languages))
         (add-to-list 'org-babel-load-languages
                      (cons (intern language) t))
         (org-babel-do-load-languages 'org-babel-load-languages
                                      org-babel-load-languages)))
     (apply orig args))))

;; Fix weird tab behavior in default org-mode. Preferable to "C-c '".
;; (use-package poly-org
;;   :defer
;;   :after org)

;; Speech-to-text in Emacs.
;; (me/emacs-N-progn
;;  30
;;  (me/eval-form-on-first-command-run
;;   whisper-run
;;   (use-package whisper
;;     :vc (:url "https://github.com/natrys/whisper.el"
;;               :rev :newest)
;;     :bind ("C-c w" . whisper-run) ;; FIXME: move this out of here?
;;     :config
;;     (setq
;;      whisper-install-directory (concat user-emacs-directory "whisper-el/")
;;      whisper-model "base"
;;      whisper-language "en"
;;      whisper-translate nil
;;      whisper-recording-timeout 600
;;      whisper--ffmpeg-input-format "alsa"
;;      whisper--ffmpeg-input-device "hw:5,0"))))

;; Read EPUBs in Emacs!
(me/setup-auto-mode
 "\\.epub"
 nov-mode
 :package nov
 (add-hook 'nov-mode-hook #'visual-line-mode))

(me/eval-form-on-first-command-run
 vterm
 (use-package vterm
   :hook (vterm-mode . (lambda () (display-line-numbers-mode 0)))))

(me/setup-auto-mode
 "\\.pdf"
 pdf-view-mode
 :package pdf-tools
 (pdf-loader-install :no-query)
 (add-hook 'pdf-view-mode-hook #'(lambda () (display-line-numbers-mode 0)))
 (add-hook 'pdf-view-mode-hook #'(lambda () (if (me/is-night-p) (pdf-view-midnight-minor-mode)))))

(me/eval-form-on-first-command-run
 eradio-play
 (use-package eradio
   :custom
   (eradio-player '("mpv" "--no-video" "--no-terminal"))
   (eradio-channels '(("def con - soma fm"      . "https://somafm.com/defcon256.pls")
                      ("the trip - soma fm"     . "https://somafm.com/thetrip.pls")
                      ("dubstep - soma fm"      . "https://somafm.com/dubstep.pls")
                      ("doomed - soma fm"       . "https://somafm.com/doomed.pls")
                      ("darkzone - soma fm"     . "https://somafm.com/darkzone.pls")
                      ("groove salad - soma fm" . "https://somafm.com/groovesalad.pls")
                      ("bossa - soma fm"        . "https://somafm.com/bossa.pls")
                      ("isl - soma fm "         . "https://somafm.com/illstreet.pls")))))

;; NOTE: They keys get bound, but they are captured by evil-mode.
;; (use-package yeetube
;;   :defer
;;   :config
;;   (defun me/open-yt-under-point ()
;;     (interactive)
;;     (let ((url (thing-at-point 'url)))
;;       (if (string-match "youtube.com" url)
;;           (yeetube-search url))))

;;   ;; Simple bit of advice to allow for youtube links to be automatically
;;   ;; searched for via yeetube.
;;   (advice-add
;;    #'browse-url
;;    :around
;;    (lambda (orig &rest args)
;;      (if (string-match "youtube.com" (car args))
;;          (yeetube-search (car args))
;;        (apply orig args))))

;;   :bind
;;   (:map yeetube-mode-map
;;         ("RET"     . yeetube-play)
;;         ("d"       . yeetube-download-video)
;;         ("/"       . yeetube-search)))


(use-package eww
  ;; Uncomment below for emacs to behave as the default web browser.
  ;; :init
  ;; (setq browse-url-browser-function 'eww-browse-url)
  :hook (eww-mode . visual-line-mode))

(me/eval-form-on-first-command-run
 elpher
 (use-package elpher
   :hook (elpher-mode . visual-line-mode)))

;;(use-package ement :defer)

;; Better LaTeX editing.

;; (use-package auctex-cluttex
;;   :after auctex)
;;(add-hook 'LaTeX-mode-hook #'auctex-cluttex-mode)



;; http://yummymelon.com/devnull/announcing-casual-an-opinionated-porcelain-for-emacs-calc.html
;; https://legends2k.github.io/note/emacs_calc/
;; (use-package casual-calc
;;   :after calc
;;   :config
;;   (define-key calc-mode-map (kbd "C-c o") #'casual-calc-tmenu))


;; (use-package exwm-setup :ensure nil)

(defun me/mu4e-have-dependencies ()
  "Return t if all dependencies for mu4e are installed, nil otherwise."
  (and
   (executable-find "msmtp")
   (executable-find "mbsync")))

;; FIXME: integrate this blogpost into mu4e-setup.el & this config.
;; https://lambdaland.org/posts/2023-05-03_email_with_outlook/
(use-package mu4e
  :defer
  :ensure nil
  :if (me/mu4e-have-dependencies)
  :config

  ;; Allow selecting files with dired.
  ;; https://www.djcbsoftware.nl/code/mu/mu4e/Dired.html
  ;; Keybind is 'C-c RET C-a' once files are marked.
  (add-hook 'dired-mode-hook #'turn-on-gnus-dired-mode)

  (setq mu4e-setup-use-msmtp-p t)
  (setq mu4e-setup-mbsync-use-master-slave-p t)
  (load-file (concat user-emacs-directory "mu4e-setup.el"))

  (setq mu4e-setup-email-profiles-list
        (list

         (mu4e-setup-email-profile
          :email-address "ethan.hawk@valpo.edu"
          :imap-address "imap.gmail.com"
          :imap-port "993"
          :smtp-address "smtp.gmail.com"
          :smtp-port "587"
          :password-command "cat /home/ethan/.config/lsps/gmail")

         (mu4e-setup-email-profile
          :email-address "masterdragoon17@hotmail.com"
          :imap-address "outlook.office365.com"
          :imap-port    "993"
          :smtp-address "smtp-mail.outlook.com"
          :smtp-port "587"
          :password-command "cat /home/ethan/.config/lsps/masterdragoon17")

         ;; Potential davmail setup below - if i ever get around to setting
         ;; it up. Maybe over winter break 2024???
         ;; (mu4e-setup-email-profile
         ;;  :email-address "ethhawk@iu.edu"
         ;;  :imap-address "127.0.0.1"
         ;;  :imap-port "1143"
         ;;  :smtp-address "127.0.0.1"
         ;;  :smtp-port "1025"
         ;;  :smtp-type "plain"
         ;;  :password-commadn "cat /home/ethan/.config/lsps/gradoutlook")
         ))

  (mu4e-setup-configure)

  (setq mail-user-agent               'mu4e-user-agent
        user-full-name                "Ethan Hawk"
        mu4e-compose-context-policy   'ask-if-none
        mu4e-context-policy           'pick-first
        mu4e-update-interval          (* 3 60)
        mu4e-completing-read-function #'completing-read
        mu4e-read-option-use-builtin  nil)

  :commands (mu4e))

;;(use-package vm)

;; (me/emacs-N-progn
;;  30
;;  (use-package tsort)
;;  (use-package kiss
;;    :ensure nil
;;    :init
;;    (unless (package-installed-p (intern "kiss"))
;;      (package-vc-install
;;       '(kiss :vc-backend Git
;;              :url "https://github.com/echawk/kiss.el")))))

;; (use-package ffi
;;   :unless noninteractive
;;   (package-vc-install
;;    '(ffi :url "https://github.com/emacs-ffi/emacs-ffi"
;;          :branch "master"
;;          :rev :newest
;;          :make "vc-install"
;;          :lisp-dir "./src"
;;          :doc "./src/emacs-ffi.texi"))
;;   )


;; (use-package xjupyter
;;   :ensure nil
;;   :init
;;   (unless (package-installed-p (intern "xjupyter"))
;;     (package-vc-install
;;      '(xjupyter :vc-backend Git
;;                 :url "https://github.com/commercial-emacs/xjupyter"))))

;; Package shannon-max is new.

;;      Status: New from melpa -- Install
;;     Archive: melpa
;;     Version: 20260505.1426
;;      Commit: 539bd5f771b798973734696b3b0ae10f56d3966d
;;     Summary: Analyze your keybindings with information theory
;;    Requires: emacs-29.1
;;     Website: https://github.com/sstraust/shannonmax
;;  Maintainer: Sam Straus <sam_straus@alumni.brown.edu>
;;      Author: Sam Straus <sam_straus@alumni.brown.edu>

;; Uses information theory to analyze your Emacs usage
;; and suggest better keybindings.

;; Add (shannon-max-start-logger) to your .emacs
;; configuration file to start collecting logs.
;; Once you have enough data, call M-x shannon-max-analyze to see the results.

;; See the project readme for more detailed instructions.



;; FUCK MACOS HAS SO MANY FUCKING UPDATES

(require 'subr-x)

(defvar me/brew-maintenance-process nil)
(defvar me/brew-maintenance-timer nil)

(defun me/run-brew-maintenance ()
  (interactive)
  (if (and me/brew-maintenance-process
           (process-live-p me/brew-maintenance-process))
      (message "Homebrew maintenance already running; skipping")
    (with-environment-variables (("NONINTERACTIVE" "1"))
      (let ((brew (executable-find "brew")))
        (unless brew
          (user-error "brew not found; check Emacs exec-path/PATH"))
        (setq me/brew-maintenance-process
              (start-process-shell-command
               "brew-maintenance"
               "*brew-maintenance*"
               (format "%s update && %s upgrade && %s cleanup"
                       (shell-quote-argument brew)
                       (shell-quote-argument brew)
                       (shell-quote-argument brew))))
        (set-process-sentinel
         me/brew-maintenance-process
         (lambda (_proc event)
           (message "Homebrew maintenance: %s" (string-trim event))))))))

;;(when (timerp me/brew-maintenance-timer)
;;  (cancel-timer me/brew-maintenance-timer))

;;(setq me/brew-maintenance-timer
;;      (run-at-time "60 min" 3600 #'me/run-brew-maintenance))


;; (run-at-time
;;  "60 min" "60 min"
;;  (lambda ()
;;    (async-shell-command "brew update")
;;    (async-shell-command "brew upgrade")
;;    (async-shell-command "brew cleanup")))
