;;; init --- my Emacs init file

;;; Commentary:

;; This is my personal Emacs configuration.  It may be of use to you,
;; as I have configured quite a number of packages.  However, there is
;; an emphasis on lightweight or builtin packages in Emacs.  Also, by
;; default, every package is explicitly deferred unless if it is
;; absolutely required at init time.  Because of this, my init time hovers
;; around 0.5 to 1 second.  This could be reduced if you don't use evil.

(defun me/package-bootstrap ()
  "Function to bootstrap package.el."
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  ;; Only install 'use-package' if Emacs version is below 29,
  ;; and if use-package is not already installed.
  (if (and (< emacs-major-version 29)
           (not (package-installed-p 'use-package)))
      (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-ensure t
        use-package-compute-statistics t))

(me/package-bootstrap)

(setq me/delete-trailing-whitespace nil)

(defmacro me/emacs-N-progn (N &rest body)
  (when (>= emacs-major-version N)
    `(progn ,@body)))

(me/emacs-N-progn
 30
 (use-package package-vc
   :ensure nil
   :demand t
   :custom
   (package-vc-allow-build-commands t)))

;; FIXME: add optional argument to determine whether or not command will be evaluated again.
(defmacro me/eval-form-on-first-command-run (command form &optional var-p)
  "Evaluate FORM when COMMAND is attempted to be ran for the first time.
COMMAND will be re-evaluated after FORM is evaluated.
If COMMAND is not redefined after evaluating FORM, an infinite loop will occur.

If VAR-P is provided, it will be used as the predicate var to determine if the
command has been ran before.
"
  (let ((comm-var-ran-p (intern
                         (concat
                          (symbol-name command)
                          "-"
                          (symbol-name (gensym))
                          "-p"))))
    (setq comm-var-ran-p (if var-p var-p comm-var-ran-p))
    `(progn
       (setq ,comm-var-ran-p (if (boundp ',comm-var-ran-p) ,comm-var-ran-p nil))
       (defun ,command ()
         "AUTOGENERATED by `me/eval-form-on-first-command-run` macro!"
         (interactive)
         (unless ,comm-var-ran-p
           (eval (quote ,form))
           (setq ,comm-var-ran-p t))
         (,command)))))

(defmacro me/eval-form-on-first-commands-run (command-lst form)
  (let ((comm-var-ran-p (intern
                         (concat
                          (symbol-name (car command-lst))
                          "-"
                          (symbol-name (gensym))
                          "-p"))))
    `(progn
       ,@(mapcar
          (lambda (comm)
            `(me/eval-form-on-first-command-run
              ,comm ,form ,comm-var-ran-p))
          command-lst))))

;; IE: only install/require the code whenever I begin to edit a file
;; with the associated file extension.
;; FIXME: re-implement in terms of me/eval-form-on-first-command-run
;; TODO: consider rewriting this macro as a use-package extension
(defmacro me/setup-auto-mode (file-extension major-mode &rest args)
  "FIXME: write this docstring."
  ;; NOTE: only use this for modes that you don't plan on configuring at all.

  ;; Default values for the use-package decl.
  (let ((pkg  major-mode)
        (mm   major-mode)
        (fe   file-extension)
        (body args))
    ;; Means we have args that we need to parse.
    (when args
      (if (eq (nth 0 args) :package)
          (progn
            (setq pkg  (nth 1 args))
            (setq body (seq-drop args 2)))))
    (let ((setup-fn-name
           (intern
            (concat
             "setup-"
             (symbol-name mm)
             "-"
             (symbol-name (gensym))))))
      `(progn
         (defun ,setup-fn-name ()
           "AUTOGENERATED from `me/setup-auto-mode` macro."
           (unless (fboundp ',mm)
             (use-package ,pkg)
             ,@body)
           (,mm))
         (add-to-list
          'auto-mode-alist
          '(,fe . ,setup-fn-name))))))

(defmacro with-var-value (var value &rest body)
  `(let ((old^ ,var))
     (unwind-protect
         (progn (setq ,var ,value) ,@body)
       (setq ,var old^))))


;; TODO: make macro to have `:hook (some-mode . (lambda () (use-package some-pkg ...)))`
;; be more seamless.

(defmacro me/eval-form-in-mode-hook (form mode-name)
  "FIXME: write this docstring"
  `(error "TODO")
  )

;; (enfun ) -- good conlang idea

(setq me/modal-system nil)
(use-package emacs
  :hook ((prog-mode . display-fill-column-indicator-mode)
         (eww-mode . visual-line-mode)
         (before-save . (lambda ()
                          ;; Somewhat better way of deleting whitespace
                          (when (or (not vc-mode) me/delete-trailing-whitespace)
                            (delete-trailing-whitespace (point-min) (point-max)))))
         (emacs-startup . (lambda ()
                            (message "Emacs loaded in %s with %d garbage collections."
                                     (format "%.2f seconds"
                                             (float-time
                                              (time-subtract after-init-time before-init-time))) gcs-done)))
         (after-save . executable-make-buffer-file-executable-if-script-p))

  :custom
  ;; Indentation
  (default-tab-width 4)
  (tab-width 4)
  (default-fill-column 80)
  (fill-column 80)

  ;; Show column number too
  (column-number-mode t)

  ;; Be more like vim when scrolling
  (scroll-step 1)
  (scroll-conservatively 10000)
  (next-screen-context-lines 5)
  (line-move-visual nil)

  ;; Don't use file backups.
  (backup-inhibited t)
  ;; Don't ask for confirmation when opening large files.
  (large-file-warning-threshold nil)

  ;; I almost NEVER want to see the warnings buffer.
  (warning-minimum-level :emergency)
  ;; Now if only I could also disable the *Compile-Log* buffer...
  (compilation-window-height 0)
  ;; Prevent any buffer from making a new window
  (display-buffer-alist '(("\\.*" . (display-buffer-no-window))))

  ;; Better buffer naming.
  (uniquify-buffer-name-style 'post-forward)

  ;; Native Compilation.
  (package-native-compile (>= emacs-major-version 28))
  (native-comp-async-report-warnings-errors (not (>= emacs-major-version 28)))

  ;; utf-8
  (default-buffer-file-coding-system 'utf-8)

  ;; Keep custom variables from polluting this file.
  (custom-file (concat user-emacs-directory "custom.el"))

  ;; Automatically visit symlink sources.
  (find-file-visit-truename t)
  (vc-follow-symlinks t)

  (use-dialog-box nil)

  ;; Don't wrap lines
  (truncate-lines t)


  ;; Make minibuffer less stuttery.
  (read-minibuffer-restore-windows nil)

  ;; Don't prompt when trying to kill a buffer with a live process.
  (kill-buffer-query-functions
   (remq 'process-kill-buffer-query-function
         kill-buffer-query-functions))

  ;; I really really cannot stand how eldoc thinks its the most important
  ;; package that likes to take over buffers that I am referring to.
  (eldoc-echo-area-prefer-doc-buffer nil)
  (eldoc-idle-delay 0)
  :config
  ;; OS specific settings.
  (cond
   ((eq system-type 'darwin)
    (progn
      ;;(setq mac-command-modifier 'control)
      (setq mac-option-modifier 'meta) ;; This is for the gui version of emacs

      ;; Emacs on macOS has now crash too many times with no reason for me to
      ;; feel comfortable disabling this.
      (setq auto-save-default t
            auto-save-timeout 30)
      ;; Only use this package on macOS. Otherwise things on Linux and BSD
      ;; behave very very incorrectly. Linux does not have the weird shell
      ;; issues that macOS has so this package hurts *far* more than it helps.
      (use-package exec-path-from-shell
        :config
        (dolist (var '("PATH"
                       "HOMEBREW_PREFIX" "HOMEBREW_CELLAR" "HOMEBREW_REPOSITORY"
                       "VIRTUAL_ENV" "PYTHONHOME"
                       "CPPFLAGS" "LDFLAGS"
                       "SSH_AUTH_SOCK" "SSH_AGENT_PID"))
          (add-to-list 'exec-path-from-shell-variables var))
        (exec-path-from-shell-initialize))))
   (t
    (progn
      (setq auto-save-default nil))))

  ;; Section to disable eldoc since I almost never want it around.
  ;; If I do, then I still have means of enabling it.

  (defvar me/eldoc-enabled-p nil)

  (defun me/eldoc-advice (orig &rest args)
    (when me/eldoc-enabled-p
      (apply orig args)))

  (advice-add 'eldoc-mode :around #'me/eldoc-advice)

  (defun me/toggle-eldoc (&optional arg)
    (interactive "P")
    (setq me/eldoc-enabled-p (if arg nil (not me/eldoc-enabled-p))))

  ;; Disable the C-scrolling keybinds
  (global-set-key (kbd "C-<wheel-up>")   #'ignore)
  (global-set-key (kbd "C-<wheel-down>") #'ignore)

  ;; Automatically update buffers when contents change on disk.
  (global-auto-revert-mode)
  ;; Always highlight the current line.
  (global-hl-line-mode)
  ;; Don't ask to spell out 'yes'
  (fset 'yes-or-no-p 'y-or-n-p)
  ;; utf-8
  (prefer-coding-system 'utf-8)
  (set-default-coding-systems 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)

  ;; ibuffer is a better version of list-buffers.
  ;; http://xahlee.info/emacs/emacs/emacs_buffer_management.html
  (defalias 'list-buffers 'ibuffer)

  ;; Prevent the scratch buffer from being killed.
  (with-current-buffer "*scratch*"
    (emacs-lock-mode 'kill))

  ;; Don't error if we can't load the custom file
  (load custom-file 'noerror)
  (setq-default indent-tabs-mode nil
                tab-width 4))

;; Elisp programming libraries
(use-package for     :defer)
(use-package eprolog :defer)
(use-package reazon  :defer)
(use-package async :defer)
;; (use-package ffi
;;   :unless noninteractive
;;   (package-vc-install
;;    '(ffi :url "https://github.com/emacs-ffi/emacs-ffi"
;;          :branch "master"
;;          :rev :newest
;;          :make "vc-install"
;;          :lisp-dir "./src"
;;          :doc "./src/emacs-ffi.texi")))


(use-package org
  :mode ("\\.org\\'" . org-mode)
  :hook
  (org-mode . jinx-mode)
  :init
  (setq org-edit-src-content-indentation 0
        org-confirm-babel-evaluate nil
        org-src-preserve-indentation t)
  :config
  (require 'org-tempo)
  ;; https://scripter.co/emacs-lisp-advice-combinators/
  (advice-add
   #'org-babel-execute-src-block
   :around
   (lambda (orig &rest args)
     (let ((language (org-element-property :language (org-element-at-point))))
       (unless (cdr (assoc (intern language) org-babel-load-languages))
         (add-to-list 'org-babel-load-languages
                      (cons (intern language) t))
         (org-babel-do-load-languages 'org-babel-load-languages
                                      org-babel-load-languages)))
     (apply orig args))))

;; Fix weird tab behavior in default org-mode. Preferable to "C-c '".
;; (use-package poly-org
;;   :defer
;;   :after org)

(use-package ux-setup
  :ensure nil
  :defer nil)
(use-package ui-setup
  :ensure nil
  :defer nil)
(use-package pl-setup
  :ensure nil
  :defer nil)
(use-package pg-setup
  :ensure nil
  :defer nil)
;; (use-package llm-setup
;;   :ensure nil
;;   :defer nil)
;; (use-package mail-setup
;;   :ensure nil
;;   :defer nil)
;; (use-package exwm-setup
;;   :ensure nil
;;   :defer nil)


;;https://github.com/jdtsmith/comint-fold

;; (use-package doom-themes :defer)

;; TODO: Break this out into a package.
;; TODO: also make a macro to help simplify the creation of
;; the functions - it should suffice to simply provide the quoted
;; code and to have that automagically be inserted into an anonymous function.
;; Semi-Configurable modeline.


;;(make-variable-buffer-local
;;(setq me/apheleia-preferred-backend (me/get-formatter-backend))

;; annotated-completing-read      20260817.235   new          melpa    Ergonomic completing-read wrapper/helper
;; auto-side-windows              20260817.1434  new          melpa    Simplified buffer management for side windows
;; card-games                     20260816.1451  new          melpa    Play card games (console UNICODE and graphical SVG)
;; ob-janet                       20260803.608   new          melpa    Org-Babel support for the Janet language
;; pgsql                          20260817.136   new          melpa    Native PostgreSQL protocol client
;; project-store                  0.9.0          new          nongnu   Project backend for Nix store
;; vice-mode                      20260810.1820  new          melpa    VIm-like Commands Extension
